import gql from 'graphql-tag';

/**
 * Admin API for the security audit trail (`SEC-006`, rebuild task R-04).
 *
 * Read-only: no mutation exists, because entries are written by the server as
 * a side effect of the actions they record. `AuditLogEntryListOptions` is
 * generated by Vendure for any query returning a `PaginatedList`.
 */
export const adminApiExtensions = gql`
    type AuditLogEntry implements Node {
        id: ID!
        createdAt: DateTime!
        updatedAt: DateTime!
        """The actor's identifier as it stood when the action happened."""
        actorIdentifier: String!
        actorUserId: ID
        ipAddress: String
        """Dotted action key, e.g. "mfa.totp.enrolled"."""
        action: String!
        targetType: String
        targetId: String
        metadata: JSON
    }

    type AuditLogEntryList implements PaginatedList {
        items: [AuditLogEntry!]!
        totalItems: Int!
    }

    extend type Query {
        auditLogEntries: AuditLogEntryList!
        auditLogEntry(id: ID!): AuditLogEntry
    }
`;
