import gql from 'graphql-tag';

/**
 * GraphQL extensions for the tailoring domain (`R-05`-style split: Admin API
 * is the workshop surface; Shop API is the customer's tracking + measurement
 * profiles). Paginated list options are auto-generated by Vendure and must
 * not be referenced here.
 */
const sharedExtensions = gql`
    enum TailoringBookingStatus {
        SCHEDULED
        COMPLETED
        CANCELLED
    }

    type TailoringJob implements Node {
        id: ID!
        createdAt: DateTime!
        updatedAt: DateTime!
        jobNumber: String!
        serviceName: String!
        orderId: ID!
        customerId: ID!
        depositPaymentId: ID
        assignedTailorId: ID
        cancelledAt: DateTime
        "Loaded by the query; null on bare list rows."
        configuration: TailoringConfiguration
        timeline: ProductionTimeline
        fittings: [FittingAppointment!]
        measurementProfile: MeasurementProfile
    }

    type TailoringJobList implements PaginatedList {
        items: [TailoringJob!]!
        totalItems: Int!
    }

    type TailoringConfiguration implements Node {
        id: ID!
        createdAt: DateTime!
        updatedAt: DateTime!
        tailoringJobId: ID!
        style: String!
        fit: String!
        fabric: String!
        color: String
        lapel: String
        buttons: String
        lining: String
        monogram: String
        designNotes: String
        referenceImageAssetIds: JSON
    }

    type MeasurementProfile implements Node {
        id: ID!
        createdAt: DateTime!
        updatedAt: DateTime!
        unit: String!
        "JSON object of measurement values."
        measurements: JSON!
        source: String!
        notes: String
        label: String
        tailoringJobId: ID
        customerId: ID!
        takenById: ID
        appointmentBookingId: ID
    }

    type MeasurementProfileList implements PaginatedList {
        items: [MeasurementProfile!]!
        totalItems: Int!
    }

    type ProductionTimeline implements Node {
        id: ID!
        createdAt: DateTime!
        updatedAt: DateTime!
        tailoringJobId: ID!
        currentStage: String!
        dueDate: DateTime
        "JSON object keyed by stage identifier (ADR-0014 §3)."
        stageTimestamps: JSON
        stageActorIds: JSON
        materialRequirements: String
        qualityControlPassed: Boolean
        notes: String
    }

    type FittingAppointment implements Node {
        id: ID!
        createdAt: DateTime!
        updatedAt: DateTime!
        tailoringJobId: ID!
        fittingType: String!
        scheduledAt: DateTime!
        durationMinutes: Int!
        location: String
        status: TailoringBookingStatus!
        notes: String
        assignedTailorId: ID
        appointmentBookingId: ID
    }

    type FittingAppointmentList implements PaginatedList {
        items: [FittingAppointment!]!
        totalItems: Int!
    }
`;

export const adminApiExtensions = gql`
    ${sharedExtensions}

    extend type Query {
        tailoringJobs(customerId: ID, orderId: ID, assignedTailorId: ID): TailoringJobList!
        tailoringJob(id: ID!): TailoringJob!
        fittings(tailoringJobId: ID, assignedTailorId: ID): FittingAppointmentList!
    }

    extend type Mutation {
        createTailoringJob(input: CreateTailoringJobInput!): TailoringJob!
        assignTailoringTailor(jobId: ID!, tailorId: ID): TailoringJob!
        cancelTailoringJob(id: ID!): TailoringJob!
        "Advances the production timeline; validates state, permissions and vocabulary (ADR-0014)."
        transitionTailoringStage(jobId: ID!, to: String!): ProductionTimeline!
        setTailoringQualityControl(jobId: ID!, passed: Boolean!): ProductionTimeline!
        upsertTailoringConfiguration(jobId: ID!, input: TailoringConfigurationInput!): TailoringConfiguration!
        createMeasurementProfile(input: MeasurementProfileInput!): MeasurementProfile!
        updateMeasurementProfile(id: ID!, input: MeasurementProfileUpdateInput!): MeasurementProfile!
        scheduleFitting(input: ScheduleFittingInput!): FittingAppointment!
        setFittingStatus(id: ID!, status: TailoringBookingStatus!): FittingAppointment!
    }

    input CreateTailoringJobInput {
        orderId: ID!
        customerId: ID!
        serviceName: String!
        jobNumber: String
        dueDate: DateTime
        assignedTailorId: ID
    }

    input TailoringConfigurationInput {
        style: String!
        fit: String!
        fabric: String!
        color: String
        lapel: String
        buttons: String
        lining: String
        monogram: String
        designNotes: String
        referenceImageAssetIds: JSON
    }

    input MeasurementProfileInput {
        customerId: ID!
        measurements: String!
        source: String!
        unit: String
        notes: String
        label: String
        tailoringJobId: ID
        takenById: ID
        appointmentBookingId: ID
    }

    input MeasurementProfileUpdateInput {
        measurements: String
        source: String
        unit: String
        notes: String
        label: String
    }

    input ScheduleFittingInput {
        tailoringJobId: ID!
        fittingType: String!
        scheduledAt: DateTime!
        durationMinutes: Int
        location: String
        assignedTailorId: ID
        notes: String
        "Optional AppointmentsPlugin slot to reserve for this fitting."
        bookSlotId: ID
    }
`;

export const shopApiExtensions = gql`
    ${sharedExtensions}

    extend type Query {
        myTailoringJobs: TailoringJobList!
        myMeasurementProfiles: MeasurementProfileList!
    }

    extend type Mutation {
        "Customer-provided measurements (source is recorded as customer_provided)."
        createMyMeasurementProfile(measurements: String!, label: String, notes: String): MeasurementProfile!
    }
`;
